### ISSUE TITLE
Create iframe for book page

### ISSUE THREAD

**Issue by Juggernaut9** [Online-Lib/OL#16]
A sticky header should appear on top of our website, below that the whole page must be an iframe for book like from gutenberg project official website

example of book link to be embedded inside iframe  - https://www.gutenberg.org/files/2274/2274-h/2274-h.htm

**Comment by agent255** [comment]
what is the header?

**Comment by agent255** [comment]
@Juggernaut9 
What is the header

**Comment by Juggernaut9** [comment]
Hey @agent255 , after pull request https://github.com/Online-Lib/OL/pull/17 gets merged to main, you can find the header in the includes folder inside views folder. The pull requests also adds a skeleton for the page which you can find in views/book.ejs which already 'includes' the header skeleton

**Comment by agent255** [comment]
yeah ok

**Comment by Juggernaut9** [comment]
feature added with https://github.com/Online-Lib/OL/pull/24
